FROM eecs388/project5

USER root

RUN cd /usr/share/john/src && \
    ./configure CFLAGS='-DJOHN_SYSTEMWIDE -DJOHN_SYSTEMWIDE_EXEC="\"/usr/share/john/run/john\"" -DJOHN_SYSTEMWIDE_HOME="\"/usr/share/john/run\""' && \
    make -s clean && make -sj$(nproc)

USER eecs388

# If you need to do any additional setup for development
# in the container like installing additional programs,
# do it in this file so that the changes are persisted.
#
# Example: to install Emacs, we might add:
#    RUN sudo apt-get update && sudo apt-get install -y emacs
